apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echodeploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echodeploy
        tier: frontend
        track: stable
    spec:
      containers:
      - name: dater
        image: busybox
        command:
        - /bin/sh
        - "-c"
        - while true; do date; sleep 1; done
---
kind: Service
apiVersion: v1
metadata:
  name: echodeploy
spec:
  type: NodePort
  selector:
    app: echodeploy
    tier: frontend
  ports:
    - protocol: TCP
      port: 4200
      targetPort: http
